# Configurações de build para o Netlify
[build]
  # Comando para construir o projeto
  command = "yarn build"
  # Diretório onde os arquivos do site construído são salvos
  publish = "dist"

# Configurações de ambiente para resolver problemas com dependências
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefer-offline"

# Redirecionamento para Single Page Applications (SPA)
# Isso garante que o React Router funcione corretamente
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200